### ISSUE TITLE
Cannot activate the extension. 

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand-Language-Support#1]
I am trying to be able to publish this extention in the VS Code repo, so users can have a great experience to   obtain it in a proper way. 

I have followed the instructions from the [documentation](https://code.visualstudio.com/docs/extensions/developing-extensions), but then when I press F5 to test it, I get an error message ```Activating extension 'ampersandtarski.language-ampersand' failed```:

![image](https://user-images.githubusercontent.com/1159672/42734413-d76cf830-8843-11e8-938a-e7e8a5757552.png)

I tried all kinds of things, but until now without luck. 

Any help is very much appreciated!

**Comment by hanjoosten** [comment]
@Michiel-s , do you know anything about this? I have the feeling it has to do with typescript / node.

**Comment by RieksJ** [comment]
I inadvertently merged your stuff with mine. Then it did not work for me any more. So I made a branch for my stuff. You should be able to get it to work for you if you follow the steps in my readme file. 

It's quite another matter to get things published. Great that you try to get this organized. I will continue to focus on the grammar and some syntax coloring stuff.

**Comment by HaaLeo** [comment]
I answered your question on [stackoverflow](https://stackoverflow.com/questions/51351243/why-does-my-new-vscode-extention-fail-to-start).

**Comment by hanjoosten** [comment]
Thanks for the answers. It helped me to get the extention compiling. @hidde-jan: Yes, I have nodejss / npm and tsc all installed, but my lack of experience with it hinderd me this time. ;)
