### ISSUE TITLE
Cannot run Ampersand compiler using Ctrl-Shift-B in version 0.2.9

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand-Language-Support#12]
My vscode has been updated to run Ampersand (ADL) language support 0.2.9.
I have complied with the requirement that the ampersand.exe is in the path: I have opened a command terminal, typed `ampersand --version`, and got the reply
~~~
14:18:41 C:\Ampersand\Git\ssif\_CZ> ampersand --version
SET AMPvsnr=Ampersand-v3.11.1 [development:e7be402f9], build time: 05-Aug-18 18:52:56 W. Europe Daylight Time
~~~
When I press Ctrl-Shift-B, and attempt to run the ampersand task, the output window contains
~~~
Error: The npm task detection didn't contribute a task for the following configuration:
{
    "type": "npm",
    "script": "compile",
    "path": "ampersandtarski.language-ampersand-0.2.8/",
    "problemMatcher": []
}
The task will be ignored.
Error: The npm task detection didn't contribute a task for the following configuration:
{
    "type": "npm",
    "script": "compile",
    "path": "ampersandtarski.language-ampersand-0.2.8/",
    "problemMatcher": []
}
The task will be ignored.
~~~
Note that in the path, it talks about version 0.2.8.
Perhaps the task should explicitly be identified as one of the contributions of the language extension?
And perhaps the path should refer to version 0.2.9?

**Comment by hanjoosten** [comment]
Did you manually add tasks in the file .vscode/tasks.json ? If so, these should never contain a reference to a specific version. 

1) Iff there are such tasks defined, remove them.
2) reinstall the extention. (just to make sure you have the latest. To do so, in vscode, press <ctrl><shift><p> and select `Developer: Reinstall Extention...`. Select the ampersand extention.

Let me know what happens.

**Comment by hanjoosten** [comment]
Our extention uses typescript. tsc is the typescript compiler. As a developer of the extention, you need it to be installed:

```
npm install -g typescript
```

If you have this installed, you should be fine.

**Comment by RieksJ** [comment]
Then I get a different error:
~~~
> language-ampersand@0.2.11 compile c:\Users\joostenhjm\.vscode\extensions\ampersandtarski.language-ampersand-0.2.11
> tsc -watch -p ./

error TS5057: Cannot find a tsconfig.json file at the specified directory: './'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! language-ampersand@0.2.11 compile: `tsc -watch -p ./`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the language-ampersand@0.2.11 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joostenhjm\AppData\Roaming\npm-cache\_logs\2018-08-12T12_07_18_343Z-debug.log
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
~~~

**Comment by hanjoosten** [comment]
With release 0.3.1, the ampersand checker daemon has been introduced. This enables the command `Ampersand: Start checker`.
