### ISSUE TITLE
Add OBJECT as keyword and represent type

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand-Language-Support#15]
Due to [Ampersand PR 871](https://github.com/AmpersandTarski/Ampersand/pull/871) which fixes [Issue 616](https://github.com/AmpersandTarski/Ampersand/issues/616), the keyword `OBJECT` will be introduced and added to the possibilities of the types in `REPRESENT <concept> TYPE <types>`.

This issue requests adding this to the VSCode language support extension.

**Comment by RieksJ** [comment]
Fixed in version 0.2.17
