### ISSUE TITLE
How to stay in sync with the compiler?

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand-Language-Support#2]
In this repo, we are putting information about the syntax of Ampersand. The ampersand compiler [also carries this information](https://github.com/AmpersandTarski/Ampersand/blob/development/src/Ampersand/Input/ADL1/Parser.hs) . We want these two to be in sync. How can we make sure that this happens?

**Comment by hanjoosten** [comment]
For reference, Keywords are maintained [here](https://github.com/AmpersandTarski/Ampersand/blob/master/src/Ampersand/Input/ADL1/Lexer.hs)

**Comment by RieksJ** [comment]
I don't have the foggiest idea just yet. Let's do things step by step. First, we'll get something to work. Then, we make sure there's a way that we can update this. Finally, we can worry about synchronicity.

**Comment by RieksJ** [comment]
Having said that, I found that the way grammars can be defined is really cool. After a learning curve it seems much more elegant than we had in EditPad Pro. It can be used to annotate even the smallest syntactical parts, which I guess is useful if (at some other point) someone makes actual editinghelperstuff, much like the editor-help I get when creating a grammar. In the medium run, this may lead to syntax modification proposals that make creating and maintaining editing support much easier. Also, I could imagine that we could have some more or less formal way of expressing the grammar such that we can generate the .tmLanguage.json file from that, as well as parser constructs for Haskell. But then, I might get a bit carried away...

**Comment by hanjoosten** [comment]
No specific work to be done. If anyone finds a discrepancy, create a specific issue for that.
