### ISSUE TITLE
different colour for template names

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand-Language-Support#27]
I have solved https://github.com/AmpersandTarski/Ampersand/issues/925, which is about the deprication of `<ROWSNH>`.

For some reason, this template is special in the syntax colouring. That should not be (any longer).

![image](https://user-images.githubusercontent.com/1159672/55967645-f2283e80-5c7a-11e9-8e72-11eab7a9fdd9.png)

**Comment by RieksJ** [comment]
You are right. Well-known BOX-types, i.e. those for which a template is provided, have a different colour than BOX-types for which users must provide a template. The idea is that developers that pay attention to the colouring of BOX-types can then detect typo's more easily. 

I will remove 'ROWSNH' from the well-known types.
