### ISSUE TITLE
Syntax checking by Ampersand itself

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand-Language-Support#3]
@Michiel-s coined the idea of having a switch in Ampersand that would allow a single file to be tested just for syntax errors, and make the resulting errors (if any) importable by VSCode. This would enable VSCode to test the syntax of texts that you edit dynamically, similar to what it does to standard languages/grammars.

Of course, this would also need to be included in the Ampersand language support...

**Comment by hanjoosten** [comment]
I like the idea. However, this is typically something to implement using a [VSCode language service](https://code.visualstudio.com/docs/extensions/overview). I will explore the possibilities to add a swich that will spin up such a language service. The syntax check will be one of the first functinality it will provide. By using the VSCode language protocol, it should be easy to integrate it with VSCode. 
Once the service is available, we have a platform to provide even more functionality later on.

**Comment by hanjoosten** [comment]
There still is some work to be done. The link in the errors opens at the top of the file. Line and column are still ignored.

**Comment by hanjoosten** [comment]
All checking is into place now. Functionality has been merged into development branch, which will go into master next release, which is [v.3.16.0](https://github.com/AmpersandTarski/Ampersand/tree/Ampersand-v3.16.0).
