### ISSUE TITLE
Propbutton snippet missing commas

### ISSUE THREAD

**Issue by SterredenBreeijen** [AmpersandTarski/Ampersand-Language-Support#34]
Ik ben een beetje aan het prutsen met die propbutton en ik kwam een foutje tegen
Maar als je een propbutton aanmaakt, vult hij automatisch aan 
~~~
                   BOX<PROPBUTTON>
                   [ property: propertyrelation cRUd
                     disabled: expression cRud
                     hide: expression cRud
                   ]
~~~
Waarna de compiler een fout geeft omdat de komma’s missen.

**Comment by RieksJ** [comment]
fixed in vsn 3.4
