### ISSUE TITLE
population snippet has too much " "

### ISSUE THREAD

**Issue by SterredenBreeijen** [AmpersandTarski/Ampersand-Language-Support#35]
Als je de snippet

`POPULATION "Relname" CONTAINS [ ("", "") ]`

gebruikt, geeft de compiler een fout omdat om Relname geen "" hoeven te staan. 

`POPULATION Relname CONTAINS [ ("", "")] `

**Comment by RieksJ** [comment]
Zal gefixt zijn in de volgende release.
