### ISSUE TITLE
Railroad tracks do not reflect effects of pull-request

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand-Language-Support#40]
@hanjoosten: some time ago I released yet another version of the langauge support. The result was that it nicely updated in VSCode, but if you look at the railroad tracks between the master and development branches, they do not show that this has been done. You noticed this already in earlier releases. This issue is to let you know this hasn't been resolved yet.

**Comment by hanjoosten** [comment]
I am still wondering what is going on, but have a hunch. It might have something to do with the way you start of a new version. Have a look: 

![image](https://user-images.githubusercontent.com/1159672/60255625-6c5a7d80-98d0-11e9-8803-b70a91aca74b.png)

It starts with a merge directly from origin. This might be the culprit. It commonly is a good idea to merge from local commits. In this specific case, you first pull the master branch, so your local master branch is in sync with the origin/master branch. Then merge that to your local development branch:
![image](https://user-images.githubusercontent.com/1159672/60256304-919bbb80-98d1-11e9-953b-49fb07ed9a17.png)

As you can see, then there is no remote-tracking branch involved in the merge. Try to make it a habit not to merge from remote stuff. Let's see if that solves this issue.

**Comment by hanjoosten** [comment]
I assume that the above mentioned way of working 'fixes' your problem. If not, feel free to reopen.
