### ISSUE TITLE
Activating extension failed - cannot find module ....\out\src\extension

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand-Language-Support#5]
When I run the debugger (F5-key) to debug langauge support, VSCode overwrites the language support for Ampersand that it normally uses with what we have in this repository, allowing me to debug stuff that is in the repo before it is deployed. Then, it tries to activate the 'new' extension.

When doing so, I get the following error:
![image](https://user-images.githubusercontent.com/8522589/42929633-ee454fe0-8b3a-11e8-8809-c4668d63c0df.png)

@hanjoosten: can you fix this?

**Comment by hanjoosten** [comment]
Yeah. I know. I have been trying out stuff yesterday eavening. I don't know what is going on here yet, got to do with typescript.

**Comment by hanjoosten** [comment]
This issue should be fixed since v 0.0.6
