### ISSUE TITLE
Update syntax for BOX attributes

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/Ampersand-Language-Support#52]
Please prepare for AmpersandTarski/Ampersand#1087

BOX attributes are introduced as described in AmpersandTarski/Ampersand#1084

**Comment by RieksJ** [comment]
1. What is it that needs preparation? 
2. I see examples of what might be expected syntax, but I do not see any specifications regarding what is (not) implemented. So how would I prepare?

**Comment by Michiel-s** [comment]
BOX syntax will be extended to support attributes. I think it would be nice to have this reflected in the VS Code plugin with syntax coloring.

@hanjoosten stated the EBNF spec that is implemented as:
```
<BoxTemplate> ::= '<' Identifier keyValPair* '>' 
<keyValPair> ::= identifier ['=' quotedString]
<quotedString> ::= '"' any-character* '"' 
```

**Comment by RieksJ** [comment]
@hanjoosten: How are the fields `Identifier` and `keyValPair*` in the `<BoxTemplate>` line distinguished from one another? Are spaces (implicitly) allowed and/or required?

**Comment by hanjoosten** [comment]
@RieksJ : The separation is done by the lexer. Whitespace closes an `Identifier` , and so does `=`.  Any quotedString is closed by a (nonexcaped) doublequote ( `"` ) character. 
Hope this helps.

**Comment by hanjoosten** [comment]
The keywords ROWS, COLS, TABS have been replaced by FORM and TABLE. Could you please apply that too? (And PANELS have never been a keyword )

**Comment by Michiel-s** [comment]
> The keywords ROWS, COLS, TABS have been replaced by FORM and TABLE. Could you please apply that too? (And PANELS have never been a keyword )

No they are not replaced. The templates are replaced and renamed, but let's not introduce these keywords in the Ampersand syntax again.

**Comment by RieksJ** [comment]
I read somewhere that `TABS` is unchanged, so I leave it in.
I will mark `ROWS` and `COLS` as illegal/deprecated. So far for backward compatibility.
I will remove `PANELS`, noting that there was a time that it was an official template (albeit not used).

**Comment by hanjoosten** [comment]
The TABS keyword is gone too. So instead of `TABS [...]` one now has to specify `BOX <TABS> [...] `. This is somewhat more verbose, but it is more consistent.

**Comment by Michiel-s** [comment]
@RieksJ maybe unnecessary to comment, but the TABS interface is still there! A search replace all will do the trick.

**Comment by RieksJ** [comment]
@hanjoosten If `BOX <TABS>` is more consistent (yet somewhat more verbose) than `TABS`, how come that logic hasn't been applied to `TABLE` and `FORM`?

**Comment by RieksJ** [comment]
Here is what I think I should be doing. Please confirm or correct:
- leave keywords `BOX`, `FORM` and `TABLE` - all the rest is deprecated.
- this may be followed by `<`, any `{Identifier}` (I won't check for system-provided templates), an optional, possibly repeated `{SpaceKeyValueString}` and a `>`. Every of these elements may have zero or more leading/trailing spaces. 
- I will use `\w+` for `{Identifier}`. It matches any nonempty string of uppercase, lowercase, digits, '-' and '_`.
- I will use `\s+\w+(="\w*")?` for {SpaceKeyValueSTring}. Note that `\s+` is needed to distinguish the upcoming identifier from preceeding stuff, particularly if that would be an identifier.
