### ISSUE TITLE
MAINTAINS statement can refer multiple rules 

### ISSUE THREAD

**Issue by hanjoosten** [AmpersandTarski/Ampersand-Language-Support#54]
The MAINTAINS statement may refer to more than one rule, that is to be maintained by (also more than one) ROLEs. Currently, if more than one RULE is specified, the colour still turns red: 

![image](https://user-images.githubusercontent.com/1159672/87954593-ded66680-caac-11ea-834e-271111f814d4.png)

**Comment by Michiel-s** [comment]
Oeh. I didn't even know that this was allowed. Good to know
