### ISSUE TITLE
Synchronization of ampersand versions used by VSCode and docker files.

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand-Language-Support#55]
According to the [documentation](https://github.com/AmpersandTarski/prototype/tree/development/templates) of `BOX <TABLE`, I should be able to write `BOX <TABLE hideNoRecords>`  in an INTERFACE, e.g. 
~~~
INTERFACE "Login" FOR Anonymous: sessionIsAnon cRud BOX <RAW>
   [ "Login bar": I-sessionAccRegForm;sessionAccRegForm~ cRud BOX <TABLE hideNoRecords>
      [ "Userid": loginUserid cRUd
      , "Password": loginPassword cRUd -- crUd is needed for Passwords
      , "IdP": loginIdP cRUd
      , "Login": I cRud BOX <PROPBUTTON> 
         [ "property": sessionLoginReq cRUd
         , "disabled": I - (loginUserid;loginUserid~ /\ loginPassword;loginPassword~) cRud
         ]
  ]
~~~
However, this produces an error: 
![image](https://user-images.githubusercontent.com/8522589/90215506-15797580-ddfc-11ea-89ae-e28209ce6b3a.png)

**Comment by hanjoosten** [comment]
Not sure how to do this. I guess some setting could be created that holds the path of the ampersand executable. That way you could point it to the correct ampersand executable.

**Comment by hanjoosten** [comment]
At least we could add a property to specify the path. [This extention](https://github.com/EFanZh/Graphviz-Preview/blob/master/package.json) could be useful as an example of how to do that. @Michiel-s is that the way to go, or should be take another approach with docker?

**Comment by Michiel-s** [comment]
I think there is a more easy way: dev containers. Just add a vs code remote container configuration to your project and you are ready to roll.

With dev containers you can specify your development environment based on a Docker image or Dockerfile. We can use the Ampersand image for that. You also specify the VS code extensions you want, in this case the Ampersand language extension.

I'll prepare an example in the ProjectAministration demo project and in the Project template repo.

**Comment by Michiel-s** [comment]
@hanjoosten @RieksJ 

Please take a look at the `.devcontainer` folder in ProjectAdministration repo: https://github.com/Michiel-s/Project-administration

You see a very small Dockerfile. Here the Ampersand compiler is copied from the image published on [Docker hub](https://hub.docker.com/r/ampersandtarski/ampersand/tags). Now it uses the `:development` tag, but you can substitute this for any published image tag (e.g. v4.0.2)

```Dockerfile
  
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

# Update the VARIANT arg in devcontainer.json to pick an Ubuntu version: focal (or ubuntu-20.04), bionic (or ubuntu-18.04)
# To fully customize the contents of this image, use the following Dockerfile instead:
# https://github.com/microsoft/vscode-dev-containers/tree/v0.128.0/containers/ubuntu/.devcontainer/base.Dockerfile
ARG VARIANT="focal"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

COPY --from=ampersandtarski/ampersand:development /bin/ampersand /usr/local/bin

# ** [Optional] Uncomment this section to install additional packages. **
#
# RUN apt-get update \
#     && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
```

Furthermore this folder contains a devcontainer configuration file (devcontainer.json). Here you can see that I've added the Ampersand extension `ampersandtarski.language-ampersand`
```json-with-comments
// For format details, see https://aka.ms/vscode-remote/devcontainer.json or this file's README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.128.0/containers/ubuntu
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick an Ubuntu version. Rebuild the container if it already
		// exists to update. Available variants: focal (or ubuntu-20.04), bionic (or ubuntu-18.04)
		"args": { "VARIANT": "focal" }
	},

	// Set *default* container specific settings.json values on container create.
	"settings": { 
		"terminal.integrated.shell.linux": "/bin/bash"
	},

	// Add the IDs of extensions you want installed when the container is created.
	"extensions": [
		"ampersandtarski.language-ampersand"
	]
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "uname -a",

	// Uncomment to use the Docker CLI from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker.
	// "mounts": [ "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind" ],

	// Uncomment when using a ptrace-based debugger like C++, Go, and Rust
	// "runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ],

	// Uncomment to connect as a non-root user. See https://aka.ms/vscode-remote/containers/non-root.
	// "remoteUser": "vscode"
}
```

To use/run this devcontainer:
1. Install the [VS Code Remote - Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers). 
2. Add the .devcontainer configuration files (both Dockerfile and devcontainer.json)
3. Open your project in the devcontainer, green button in bottom-left corner (or ctrl-shift p -> Remote Containers : open folder in container)


**NOTE Issue with line endings**
There is an issue with difference in line endings between windows (CRLF) and linux (LF) that you need to keep in mind. The Ampersand daemon that is available in the devcontainer is a linux binary, that expects only LF. Probably your `.ampersand` file has CRLF line endings, which cases that the daemon cannot find the mentioned file. Simply change the line ending to LF (bottom-right corner is VS Code) and you're ready to go.

**Comment by RieksJ** [comment]
Cool. I guess it would be appropriate to allow users to configure some things a little bit. So for default (novice-grade) development, a docker file that is 'internal' to the daemon would suffice, which could use the latest release of the &-executable. However, in order to allow more configuration (e.g. use a specific version of the &-executable, and perhaps assemble some reusable modules such as SIAM, TText, etc.), we might want to have a `.docker` file (similar to the `.ampersand` file).

**Comment by Michiel-s** [comment]
> Cool. I guess it would be appropriate to allow users to configure some things a little bit. So for default (novice-grade) development, a docker file that is 'internal' to the daemon would suffice, which could use the latest release of the &-executable. However, in order to allow more configuration (e.g. use a specific version of the &-executable, and perhaps assemble some reusable modules such as SIAM, TText, etc.), we might want to have a `.docker` file (similar to the `.ampersand` file).

I'm not sure if I understand what you mean. The idea of a .devcontainer configuration is that it is project specific. You check these file in under version control. That way your development environment is portable to other developers as well. If need need specific steps (e.g. copy a SIAM module to your project environment) you can specify this in the Dockerfile of the .devcontainer.
I don't think we need some other configuration file.

**Comment by Michiel-s** [comment]
Instead of using the compiler from its image, you can also download the compiler from Github releases page: https://github.com/AmpersandTarski/Ampersand/releases

Use ADD command as shown below

```Dockerfile
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

# Update the VARIANT arg in devcontainer.json to pick an Ubuntu version: focal (or ubuntu-20.04), bionic (or ubuntu-18.04)
# To fully customize the contents of this image, use the following Dockerfile instead:
# https://github.com/microsoft/vscode-dev-containers/tree/v0.128.0/containers/ubuntu/.devcontainer/base.Dockerfile
ARG VARIANT="focal"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

ADD https://github.com/AmpersandTarski/Ampersand/releases/download/Ampersand-v4.1.0/ampersand /usr/local/bin/ampersand
RUN chmod +x /usr/local/bin/ampersand
# COPY --from=ampersandtarski/ampersand:development /bin/ampersand /usr/local/bin

# ** [Optional] Uncomment this section to install additional packages. **
#
# RUN apt-get update \
#     && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
```

**Comment by RieksJ** [comment]
Ok. That part works fine, so we can close this issue (for it to work more or less as before, AmpersandTarski/Ampersand#1107 needs to be resolved).
